version: '3.8'

services:
  # Simple intelligent agent app
  app:
    build:
      context: ../..
      dockerfile: docker/Dockerfile.basic
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_key_here}
      - DEBUG=true
      - DATABASE_URL=sqlite:///./data/app.db
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Simple database viewer (for SQLite)
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=app
    depends_on:
      - app
    profiles:
      - admin

volumes:
  app_data:
